# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mixed Random Variables
email: onur.tunali@itu.edu.tr
description: > # this means to ignore newlines until "baseurl:"
  This is the official website and blog of Onur Tunali which covers topics about CS,  mathematics and machine learning with in depth review of textbooks.
paginate: 5
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username:
github_username: onurtunali
scholar_username: https://scholar.google.com.tr/citations?user=tz3gufIAAAAJ&hl=en
# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
encoding: utf-8
plugins: [jekyll-paginate]
